/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import project.views.Main;

public class App {
    public String getGreeting() {
        return "Hello from App";
    }

    public static void main(String[] args) {
        Main main = new Main();
        main.show();
    }
}
